certification_app/config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     '/help',                      to: 'static_pages#help'
  get     '/about',                     to: 'static_pages#about'
  get     '/contact',                   to: 'static_pages#contact'

  get     '/signup',                    to: 'users#new'
  get     '/users/:public_addr',        to: 'users#show',                 as: 'user'
  get     '/users/edit/:public_addr',   to: 'users#edit',                 as: 'edit'
  get     '/login',                     to: 'sessions#new'

  get     '/courses',                   to: 'courses#all'
  get     '/courses/add_course',        to: 'courses#new',                as: 'add_course'
  get     '/courses/:id',               to: 'courses#show',               as: 'course'

  get     '/admin/:hashed_id',          to: 'admin#all',                  as: 'admin'

  get     '/verify',                    to: 'verify#get'

  post    '/login',                     to: 'sessions#create'
  post    '/signup',                    to: 'users#create'

  post    '/users/edit/:public_addr',   to: 'users#update',               as: 'update'

  post    '/courses/add_course',        to: 'courses#create'
  post    '/courses/:id',               to: 'courses#update'

  post    '/admin/:hashed_id',          to: 'admin#submit',               as: 'admin_post'

  post    '/verify',                    to: 'verify#post'

  delete  '/logout',                    to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

certification_app/app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="copyright">
      <small>
        <a href="https://github.com/ayush268/certification">Code</a>
      </small>
    </div>
    <div class="credits">
      <nav>
        <ul>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</footer>

certification_app/app/views/layouts/_header.html.erb
<header id="header" class="">
  <div class="container">
    <div id="logo" class="pull-left">
      <%= link_to image_tag("dragon.jpg"), root_path, class: "scrollto" %>
    </div>
    <nav id="nav-menu-container">
      <ul class="nav-menu sf-js-enabled" style="touch-action: pan-y;">
        <li><%= link_to "Course Catalog",    courses_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <% if logged_in? %>
          <li class="sf-arrows">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="sf-with-ul">
              <li><%= link_to "Courses Taken", user_path(current_user[:public_addr]) %></li>
              <li><%= link_to "Edit Profile", edit_path(current_user[:public_addr]) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        	<li class="buy-tickets"><%= link_to "Register", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

certification_app/app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

certification_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

certification_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
    <%= render 'layouts/footer' %>    
  </body>
</html>