certification_app/config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     '/help',                      to: 'static_pages#help'
  get     '/about',                     to: 'static_pages#about'
  get     '/contact',                   to: 'static_pages#contact'

  get     '/signup',                    to: 'users#new'
  get     '/users/:public_addr',        to: 'users#show',                 as: 'user'
  get     '/users/edit/:public_addr',   to: 'users#edit',                 as: 'edit'
  get     '/login',                     to: 'sessions#new'

  get     '/courses',                   to: 'courses#all'
  get     '/courses/add_course',        to: 'courses#new',                as: 'add_course'
  get     '/courses/:id',               to: 'courses#show',               as: 'course'

  get     '/admin/:hashed_id',          to: 'admin#all',                  as: 'admin'

  get     '/verify',                    to: 'verify#get'

  post    '/login',                     to: 'sessions#create'
  post    '/signup',                    to: 'users#create'

  post    '/users/edit/:public_addr',   to: 'users#update',               as: 'update'

  post    '/courses/add_course',        to: 'courses#create'
  post    '/courses/:id',               to: 'courses#update'

  post    '/admin/:hashed_id',          to: 'admin#submit',               as: 'admin_post'

  post    '/verify',                    to: 'verify#post'

  delete  '/logout',                    to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

certification_app/app/models/user.rb
class User < ApplicationRecord
  self.primary_key = 'public_addr'

  attr_accessor :remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 30 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :public_addr, presence: true, length: {is: 40}, uniqueness: true

  has_many :courses
  has_many :user_course_mappings
  has_many :courses_taken, class_name: 'Course', through: :user_course_mappings, :source => :course

  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }

  # Returns the hash digest of the given string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

end

certification_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if not logged_in?
      redirect_to login_path
    else
      if current_user[:public_addr] == params[:public_addr]
        @user = User.find(params[:public_addr])
        courses_offered = @user.courses.select{ |c| c.accepted }.map do |course|
          {
            id: course.id,
            no: course.course_no,
            session: course.course_session,
            desc: course.course_desc,
            status: course_status(course),
            inst: course.user
          }
        end
        course_mappings = @user.user_course_mappings
        courses_taken = course_mappings.select{ |m| m.course.accepted }.map do |m|
          {
            id: m.course.id,
            no: m.course.course_no,
            session: m.course.course_session,
            desc: m.course.course_desc,
            status: course_status(m.course),
            inst: m.course.user
          }
        end
        @courses = courses_offered + courses_taken
      else
        redirect_to user_path(current_user[:public_addr])
      end
    end
  end

  def new
    if logged_in?
      redirect_to user_path(current_user[:public_addr])
    end
    puts(params)
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Certification!"
      redirect_to user_path(@user[:public_addr])
    else
      render 'new'
    end
  end

  def edit
    if not logged_in?
      redirect_to login_path
    else
      if current_user[:public_addr] == params[:public_addr]
        @user = User.find(params[:public_addr])
      else
        redirect_to user_path(current_user[:public_addr])
      end
    end
  end

  def update
    if not logged_in?
      redirect_to login_path
    end
    @user = current_user
    if @user.update(update_user_params)
      flash[:success] = "Profile Updated Successfully!"
      redirect_to user_path(@user[:public_addr])
    else
      render 'edit'
    end
  end

  private
    
    def user_params
      params.require(:user).permit(:name, :username, :email,
                                   :password, :password_confirmation,
                                   :public_key, :public_addr)
    end

    def update_user_params
      params.permit(:name, :username, :email)
    end

    def get_keys
      token = get_token
      response = HTTParty.post("https://api.blockcypher.com/v1/eth/main/addrs", body: { token: token })
      return_val = {}
      return_val[:public_addr] = response["address"]
      return_val[:public_key] = response["public"]
      return_val[:private_key] = response["private"]
      return_val
    end

end

certification_app/app/helpers/users_helper.rb
module UsersHelper

  def get_token
    tokens = ["18f9090ae22541768e5311cfa19fe96c", "403f37d1cfd74ce9ad6622e9f0a8207f"]
    num = Random.rand(tokens.size)
    tokens[num]
  end

end

certification_app/app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<section id="contact" class="section-bg wow" style="visibility:visible;">
  <div class="container">
    <div class="section-header">
      <h2> Edit Profile </h2>
    </div>

    <div class="form">
        <%= form_tag(controller: 'users', action: 'update', method: 'post') do %>
          <div class="form-group col-md-6 col-md-offset-3">
            <%= label_tag(:name, "Name") %>
            <%= text_field_tag(:name, params[:name], class: "form-control") %>
          </div>
          <div class="form-group col-md-6 col-md-offset-3">
            <%= label_tag(:username, "Username") %>
            <%= text_field_tag(:username, params[:username], class: "form-control") %>
          </div>
          <div class="form-group col-md-6 col-md-offset-3">
            <%= label_tag(:email, "Email") %>
            <%= email_field_tag(:email, params[:email], class: "form-control") %>
          </div>
          <div class="text-center">
          <%= submit_tag "Update", {:class =>"btn btn-primary"} %>
        </div>
        <% end %>
    </div>
  </div>
</section>

certification_app/app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<section id="contact" class="section-bg wow" style="visibility:visible;">
  <div class="container">
    <div class="section-header">
      <h2> Sign up </h2>
    </div>

    <div class="form">
        <%= form_for(@user, url: signup_path) do |f| %>
          <%= render 'shared/user_error_messages' %>

          <div class="form-group col-md-6 col-md-offset-3">
            <%= f.label :name %>
            <%= f.text_field :name, id: 'name', class: 'form-control' %>
          </div>

          <div class="form-group col-md-6 col-md-offset-3">
          <%= f.label :username %>
          <%= f.text_field :username, id: 'username', class: 'form-control' %>
          </div>

          <div class="form-group col-md-6 col-md-offset-3">
          <%= f.label :email %>
          <%= f.email_field :email, id: 'email', class: 'form-control' %>
          </div>

          <div class="form-group col-md-6 col-md-offset-3">
          <%= f.label :password %>
          <%= f.password_field :password, id: 'password', class: 'form-control' %>
          </div>

          <div class="form-group col-md-6 col-md-offset-3">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, id: 'password_confirmation', class: 'form-control' %>
          </div>

          <div class="text-center">
            <button type="button" onClick='javascript:signup()'>Create My Account</button>
          </div>
        <% end %>
    </div>
  </div>
</section>

certification_app/app/views/users/show.html.erb
<% provide(:title, "Courses Taken") %>
<section id="faq" class="wow" style="visibility: visible;">
  <div class="container">
    <div class="section-header">
      <h2><%= "Hi " + current_user[:name] %></h2>
    </div>
    <div class="row justify-content-center">
      <div class="container-table100">
        <div class="wrap-table100">
          <div class="table100 ver4 m-b-110">
            <div class="table100-head">
              <table>
                <thead>
                  <tr class="row100 head">
                    <th class="cell100 column1">Course No</th>
                    <th class="cell100 column2">Session</th>
                    <th class="cell100 column3">Status</th>
                    <th class="cell100 column4">Instructor</th>
                  </tr>
                </thead>
              </table>
            </div>
            <div class="table100-body js-pscroll">
              <table>
                <tbody>
                  <% @courses.each do |course| %>
                    <tr class="row100 body">
                      <%= content_tag(:td, class: ["cell100", "column1"]) do %>
                        <%= link_to course[:no], course_path(course[:id])%>
                      <% end %>
                      <%= content_tag(:td, course[:session], class: ["cell100", "column2"] ) %>
                      <%= content_tag(:td, course[:status], class: ["cell100", "column3"]) %>
                      <%= content_tag(:td, course[:inst][:name], class: ["cell100", "column4"]) %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <br><br>
              <p>Want to see all the courses? <%= link_to "Course Catalog!", courses_path %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>