certification_app/config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     '/help',                      to: 'static_pages#help'
  get     '/about',                     to: 'static_pages#about'
  get     '/contact',                   to: 'static_pages#contact'

  get     '/signup',                    to: 'users#new'
  get     '/users/:public_addr',        to: 'users#show',                 as: 'user'
  get     '/users/edit/:public_addr',   to: 'users#edit',                 as: 'edit'
  get     '/login',                     to: 'sessions#new'

  get     '/courses',                   to: 'courses#all'
  get     '/courses/add_course',        to: 'courses#new',                as: 'add_course'
  get     '/courses/:id',               to: 'courses#show',               as: 'course'

  get     '/admin/:hashed_id',          to: 'admin#all',                  as: 'admin'

  get     '/verify',                    to: 'verify#get'

  post    '/login',                     to: 'sessions#create'
  post    '/signup',                    to: 'users#create'

  post    '/users/edit/:public_addr',   to: 'users#update',               as: 'update'

  post    '/courses/add_course',        to: 'courses#create'
  post    '/courses/:id',               to: 'courses#update'

  post    '/admin/:hashed_id',          to: 'admin#submit',               as: 'admin_post'

  post    '/verify',                    to: 'verify#post'

  delete  '/logout',                    to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

certification_app/app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def all
    if not logged_in?
      redirect_to login_path
    else
      courses = Course.all.select{ |course| course.accepted }
      @courses = []
      if courses.size != 0
        @courses = courses.map do |course|
          {
            id: course.id,
            no: course.course_no,
            session: course.course_session,
            desc: course.course_desc,
            status: course_status(course),
            inst: course.user
          }
        end
      end
    end
  end

  def new
    if not logged_in?
      redirect_to login_path
    end
    @course = Course.new
  end

  def create
    if not logged_in?
      redirect_to login_path
    end
    user_id = current_user[:public_addr]
    final_params = {accepted: false, user_id: user_id}
    final_params.reverse_merge!(course_params)
    @course = Course.new(final_params)
    if @course.save
      flash[:success] = "Your course request has gone for approval!"
      redirect_to user_path(user_id)
    else
      render 'new'
    end
  end

  def show
    if not logged_in?
      redirect_to login_path
    else
      #TODO Complete this function
      @course = Course.find(params[:id])
      if not @course.accepted
        redirect_to courses_path
      end

      case inst_or_student_or_else?(@course)
        when 1
          @students = @course.user_course_mappings.map do |m|
            {
              name: m.user.name,
              username: m.user.username,
              addr: m.user.public_addr,
              status: m.accepted,
              passed: m.passed,
              email: m.user.email
            }
          @mappings = @course.user_course_mappings.select{ |x| not x.accepted }
          @accepted_mappings = @course.user_course_mappings.select{ |x| x.accepted }
          end
          render 'inst_page'
        when 2
          @mapping = UserCourseMapping.where(user_id: current_user[:public_addr], course_id: @course[:id])[0]
          render 'accepted_page'
        when 3
          render 'rejected_page'
        else
          render 'other_people_page'
      end

    end
  end

  def update
    @course = Course.find(params[:id])
    if params[:commit] == "Register"
      if register_student(params[:id])
        flash[:success] = "Your course request has been sent to the instructor for approval!"
        redirect_to user_path(current_user[:public_addr])
      else
        redirect_to course_path(params[:id])
      end
    end
    if params[:commit] == "Approve Requests"
      accepted_mappings = params[:accepted_users][:id]
      accepted_mappings.select!{ |v| v.to_i != 0 }

      cert_hash_list = {}
      cert_list = {}
      accepted_mappings.each do |id|
        m = UserCourseMapping.find(id)
        cert_hash_list[id], cert_list[id] = approve_student(m)
        m.update(accepted: true)
      end

      result = getRootHash(cert_hash_list.values)
      rootHash = result['rootHash']
      tokenList = result['tokenList']

      registerstudents(rootHash, params[:private_key], @course[:contract_addr], "1")

      accepted_mappings.each do |id|
        m = UserCourseMapping.find(id)
        comp_cert = cert_list[id]
        hash = cert_hash_list[id]
        json_data = tokenList[hash].to_json
        comp_cert.update(transaction_hash: rootHash, tokens: json_data)
      end

      redirect_to user_path(current_user[:public_addr])
    end
    if params[:commit] == "Submit Grades"
      passed_mappings = params[:passed_users][:id]
      passed_mappings.select!{ |v| v.to_i != 0 }

      cert_hash_list = {}
      cert_list = {}
      passed_mappings.each do |id|
        m = UserCourseMapping.find(id)
        cert_hash_list[id], cert_list[id] = pass_student(m)
        m.update(passed: true)
      end

      result = getRootHash(cert_hash_list.values)
      rootHash = result['rootHash']
      tokenList = result['tokenList']

      registerstudents(rootHash, params[:private_key], @course[:contract_addr], "0")

      passed_mappings.each do |id|
        m = UserCourseMapping.find(id)
        accept_cert = cert_list[id]
        hash = cert_hash_list[id]
        json_data = tokenList[hash].to_json
        accept_cert.update(transaction_hash: rootHash, tokens: json_data)
      end

      redirect_to user_path(current_user[:public_addr])
    end
  end

  private

    def course_params
      params.require(:course).permit(:course_no, :course_session, :course_desc)
    end

    def inst_or_student_or_else?(course)
      if current_user[:public_addr] == course.user[:public_addr]
        return 1
      end
      users = course.user_course_mappings
      users_accepted = users.select{ |m| m.accepted }.map{ |x| x.user.public_addr }
      users_rejected = users.select{ |m| not m.accepted }.map{ |x| x.user.public_addr }
      if users_accepted.include? current_user[:public_addr]
        return 2
      elsif users_rejected.include? current_user[:public_addr]
        return 3
      end
      return 4
    end

    def register_student(course_id)
      mapping = UserCourseMapping.new(user_id: current_user[:public_addr], course_id: course_id, accepted: false, passed: false)
      if mapping.save
        return true
      else
        return false
      end
    end

    def approve_student(mapping)
      comp_cert = CompCert.new(user_id: mapping[:user_id], course_id: mapping[:course_id], desc: "Tu accept ho gaya launde")
      comp_cert.save

      hash = Digest::MD5.new
      hash << comp_cert.to_json
      hash = hash.hexdigest
      return hash, comp_cert
    end

    def pass_student(mapping)
      accept_cert = AcceptCert.new(user_id: mapping[:user_id], course_id: mapping[:course_id], desc: "Tu pass ho gaya launde")
      accept_cert.save

      hash = Digest::MD5.new
      hash << accept_cert.to_json
      hash = hash.hexdigest
      return hash, accept_cert
    end

    def getRootHash(hash_list)
      args = ""
      hash_list.each do |x|
        args = args + x + " "
      end
      python_script = Rails.root.join('python_scripts/merkle_tree.py')
      result = `python #{python_script} #{args}`
      puts(result)
      result = JSON.parse(result)
      return result
    end

    def registerstudents(rootHash, private_key, contractAddress, accept_complete)
      key = Eth::Key.new priv: private_key
      sighash = key.personal_sign(rootHash)
      @admin = Admin.all[0]
      arg1 = "0x" + @admin.private_key
      arg2 = "0x" + @admin.public_addr
      arg3 = hash
      arg4 = sighash
      arg5 = contractAddress
      arg6 = accept_complete

      python_script = Rails.root.join('python_scripts/addRootHash.py')
      result = `python #{python_script} #{arg1} #{arg2} #{arg3} #{arg4} #{arg5} #{arg6}`
      return result
    end
end

certification_app/app/helpers/courses_helper.rb
module CoursesHelper


  def course_status(course)

    # Periods are assumed in hours
    registration_period = 1
    course_period = registration_period + 1

    hours_elapsed = (DateTime.now.to_i - course.accepted_time.to_i) / 60
    case true
      when hours_elapsed < registration_period
        return "Registration Period"
      when hours_elapsed < course_period
        return "Course Ongoing"
      else
        return "Course Completed"
    end

  end


end

certification_app/app/views/courses/accepted_page.html.erb
<% provide(:title, "Course HomePage") %>
<h1><%= @course[:course_no] + ", " + @course[:course_session] %></h1>
<p>
  <% if course_status(@course) == "Registration Period" %>
    <%= "Request is sent to the instructor" %>
  <% elsif course_status(@course) == "Course Ongoing" %>
      <a href="/certificate.json">Download Acceptance Certificate</a>
  <% else %>
    <% if @mapping[:passed] %>
      <a href="/certificate.json">Download Acceptance Certificate</a>
    <% else %>
      <a href="/certificate.json">Download Completion Certificate</a>
    <% end %>
  <% end %>
</p>

certification_app/app/views/courses/all.html.erb
<% provide(:title, "Courses Catalog") %>
<section id="faq" class="wow" style="visibility: visible;">
  <div class="container">
    <div class="section-header">
      <h2>All Courses Offered</h2>
    </div>
        <div class="row justify-content-center">
      <div class="container-table100">
        <div class="wrap-table100">
          <div class="table100 ver4 m-b-110">
            <div class="table100-head">
              <table>
                <thead>
                  <tr class="row100 head">
                    <th class="cell100 column1">Course No</th>
                    <th class="cell100 column2">Session</th>
                    <th class="cell100 column3">Status</th>
                    <th class="cell100 column4">Instructor</th>
                  </tr>
                </thead>
              </table>
            </div>
            <div class="table100-body js-pscroll">
              <table>
                <tbody>
                  <% @courses.each do |course| %>
                    <tr class="row100 body">
                      <%= content_tag(:td, class: ["cell100", "column1"]) do %>
                        <%= link_to course[:no], course_path(course[:id])%>
                      <% end %>
                      <%= content_tag(:td, course[:session], class: ["cell100", "column2"] ) %>
                      <%= content_tag(:td, course[:status], class: ["cell100", "column3"]) %>
                      <%= content_tag(:td, course[:inst][:name], class: ["cell100", "column4"]) %>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <br><br>
              <p>Want to offer a course? <%= link_to "Add a Course!", add_course_path %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

certification_app/app/views/courses/inst_page.html.erb
<% provide(:title, "Course HomePage") %>
<section id="contact" class="section-bg wow" style="visibility:visible;">
  <div class="container">
    <div class="section-header">
      <h2><%= @course[:course_no] + ", " + @course[:course_session] %></h2>
    </div>
    <div class="tab-content row justify-content-center">
      <div id="day-1" class='col-lg-9 tab-pane show active' role='tabpanel'>
        <% if course_status(@course) == "Registration Period" %>
          <%= form_tag(controller: 'courses', action: 'update', method: 'post') do %>
              <%= collection_check_boxes(:accepted_users, :id, @mappings, :id, :get_user_info) do |b| %>
                <div class="row">
                  <%= b.label %>
                  <%= b.check_box %>
                </div>
              <% end %>
              <div class="row">
                <%= label_tag(:private_key, "Private Key") %>
                <%= text_field_tag(:private_key, params[:private_key]) %>
              </div>
              <div class="row">
                <%= submit_tag "Approve Requests", {:class =>"fancy-button"} %>
              </div>
          <% end %>
        <% elsif course_status(@course) == "Course Ongoing" %>
          <%= form_tag(controller: 'course', action: 'update', method: 'post') do %>
              <%= collection_check_boxes(:passing_users, :id, @accepted_mappings, :id, :get_user_info) do |b| %>
                <div class="row">
                  <%= b.label %>
                  <%= b.check_box %>
                </div>
              <% end %>
              <div class="row">
                <%= submit_tag "Submit Grades", {:class =>"fancy-button"} %>
              </div>
          <% end %>
        <% else %>
          <div class="row">
            <%= "Course is Over!" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

certification_app/app/views/courses/new.html.erb
<% provide(:title, "Add a Course") %>
<section id="contact" class="section-bg wow" style="visibility:visible;">
  <div class="container">
    <div class="section-header">
      <h2>Add a Course</h2>
    </div>

    <div class="form">
        <%= form_for(@course, url: add_course_path) do |f| %>
          <%= render 'shared/course_error_messages' %>

          <div class="form-group col-md-6 col-md-offset-3">
            <%= f.label :course_no %>
            <%= f.text_field :course_no, class: 'form-control' %>
          </div>

          <div class="form-group col-md-6 col-md-offset-3">
            <%= f.label :course_session %>
            <%= f.text_field :course_session, class: 'form-control' %>
          </div>

          <div class="form-group col-md-6 col-md-offset-3">
            <%= f.label :course_desc %>
            <%= f.text_field :course_desc, class: 'form-control' %>
          </div>

          <div class="text-center">
            <%= f.submit "Add this Course", class: "btn btn-primary" %>
          </div>
        <% end %>
    </div>
  </div>
</section>

certification_app/app/views/courses/other_people_page.html.erb
<% provide(:title, "Course HomePage") %>
<section id="contact" class="section-bg wow" style="visibility:visible;">
  <div class="container">
    <div class="section-header">
      <h2><%= @course[:course_no] + ", " + @course[:course_session] %></h2>
    </div>
    <div class="tab-content row justify-content-center">
      <div id="day-1" class='col-lg-9 tab-pane show active' role='tabpanel'>
        <div class="row">
          <% if course_status(@course) == "Registration Period" %>
            <%= form_tag(controller: 'courses', action: 'update', method: 'post') do %>
              <% params[:enroll] = true %>
              <%= submit_tag "Register", {:class =>"fancy-button"} %>
            <% end %>
          <% elsif course_status(@course) == "Course Ongoing" %>
            <%= "Course Registration Deadline has passed!" %>
          <% else %>
            <%= "Course Registration Deadline has passed!" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

certification_app/app/views/courses/rejected_page.html.erb
<% provide(:title, "Course HomePage") %>
<section id="contact" class="section-bg wow" style="visibility:visible;">
  <div class="container">
    <div class="section-header">
      <h2><%= @course[:course_no] + ", " + @course[:course_session] %></h2>
    </div>
    <div class="tab-content row justify-content-center">
      <div id="day-1" class='col-lg-9 tab-pane show active' role='tabpanel'>
	    <div class="row">
	    	<% if course_status(@course) == "Registration Period" %>
			  <%= "Request is sent to the instructor" %>
			<% elsif course_status(@course) == "Course Ongoing" %>
			  <%= "You were rejected from the course!" %>
			<% else %>
			  <%= "You were rejected from the course!" %>
			<% end %>
	    </div>
      </div>
    </div>
  </div>
</section>